---

name: Baro Release v0.2.0
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: true

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL \
          https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
          | sh -s -- -b /usr/local/bin

      - name: Install Grype
        run: |
          curl -sfL \
          https://raw.githubusercontent.com/anchore/grype/main/install.sh \
          | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run: |
          trivy fs . \
          --format cyclonedx \
          -o baro-sbom.cdx.json

      - name: Scan Baro SBOM
        run: |
          grype sbom:baro-sbom.cdx.json \
          --fail-on critical

      - name: Build artifact
        run: |
          tar -czf Baro.jl-${{ github.ref_name }}.tar.gz \
          --exclude='.git' \
          --exclude='.github' \
          .
      - name: Attest Build Provenance - Baro
        uses: actions/attest@v4
        with:
          subject-path: 'Baro.jl-${{github.ref_name }}.tar.gz'
